### ISSUE TITLE
main: line 1159: efibootmgr: command not found

### ISSUE THREAD

**Issue by thethinker990** [saveriomiroddi/zfs-installer#124]
Hi, I got this bug the last time too, I had to restart the whole installer and first install this software. If I install all the mandatory software (like zfsutils, etc) in front I get also a bug.

Sidenote: it would be nice, if you put `devices=off` in your list of tweaks, because I got another error because of double this tweak.

Edit: Ubuntu Server LTS 20.04 with updated installer 20.05.1 - but the version of installer don't take effect on `efibootmgr` (tested)

**Comment by nlfog** [comment]
I can confirm this issue as well, just ran into it on my install.

**Comment by saveriomiroddi** [comment]
Hello! Sorry for the inconvenience. I've just release a fix for the issue. Regarding the `devices=off`, it'd be best to create a new issue, as I handle issues atomically, for a variety of reasons (e.g. one being more difficult than another).

**Comment by saveriomiroddi** [comment]
@thethinker990 in relation to `devices=off`, please open a new issue with as many details as possible (and reasonable) - at a quick glance, `devices=off` is already in the pool attributes:

```sh
  zpool create \
    "${encryption_options[@]}" \
    "${v_rpool_tweaks[@]}" \
    -O devices=off -O mountpoint=/ -R "$c_zfs_mount_dir" -f \
    "$v_rpool_name" $v_pools_raid_type "${rpool_disks_partitions[@]}" \
    < "$c_passphrase_named_pipe"

  # `-d` disable all the pool features (not used here);
  #
  # shellcheck disable=SC2086 # see above
  zpool create \
    "${v_bpool_tweaks[@]}" \
    -O devices=off -O mountpoint=/boot -R "$c_zfs_mount_dir" -f \
    "$v_bpool_name" $v_pools_raid_type "${bpool_disks_partitions[@]}"
```
