### ISSUE TITLE
error if `devices` is two times passed

### ISSUE THREAD

**Issue by thethinker990** [saveriomiroddi/zfs-installer#126]
Hi, as you recommended I open another issue for the `devices` bug/error

I wrote down all my custom tweaks in the GUI, as well the `devices=off` option because of security measures.

After the installation (ubiquity) if I press enter in your GUI the installation stops at some point with the message "devices is already defined" (or similar, IDK the exact words)

I ran into this problem two times, the first time I didn't understand it, I think it was just a bug or racing condition. The second time I'd get it, because I passed `devices=off`. I checked it in the Shell-Script and I've seen the argument there. So I didn't give it the next time and everything worked fine.

**Comment by saveriomiroddi** [comment]
Thanks!

So, to understand - what should be done? Is this a UX issue, that is, I should make it clear that the user does _not_ need to add the option? Or, add it to the tweaks instead?

If so, I think the first would be best, as `devices=off`is not a tweak itself.

**Comment by thethinker990** [comment]
1. I think it's a UI issue. You should create probably another side with "not tweaks" 
2. Or you make it clear that this option is already enabled. 

It's your choice at all, I personally would create option 1.

**Comment by saveriomiroddi** [comment]
Fixed (by improving the dialog messages), although it will be released once I make other changes.
