### ISSUE TITLE
Proposed enhancements: move root to separate datasets

### ISSUE THREAD

**Issue by selbitschka** [saveriomiroddi/zfs-installer#135]
Hi,

first of all many thanks for your work - the script is great.
I recently installed my notebook with Mint 20 using an enhanced version of you script.

My enhancements are:
- Move the encryption from pool (rpool) to a separate (parent) dataset 'encrypted', to allow unencrypted datasets.
- Put data into datasets not the pool itself, therefore I introduced a 'boot' and 'root' dataset.
- Implementing options for splitting data to multiple dataset for /home, /var, /opt.

Now the question is, are you interested an should I create a pull request - or should I create a fork on my own git?

regards

stefan

**Comment by pepa65** [comment]
Please publish your fork regardless!

**Comment by saveriomiroddi** [comment]
Hello @selbitschka/Stefan!

This is very interesting - as a matter of fact, I've been wanting to support this:

> Implementing options for splitting data to multiple dataset for /home, /var, /opt.

for a long time.

Now, there are two problems, one minor and one major.

## Feature splitting

The minor is that changes like the above should be split into multiple PRs. This is generally a matter of good practice, however, when it comes to contributions, if one feature requires more work than another, the latter can go in more quckly; additionally, splitting allows testing in isolation, which is particularly important for a project like this, where testing is hard.

All in all though, this is not a big deal (I hope :wink:)

## UX

The major problem is UX. Without knowing your code, features for personal use are developed without a generic audience in mind, so there may be hurdles when making the feature generic.

There could also be technical complexities hidden. The official guide by the ZFS guys employs a significant customization for each (sub) filesystem (e.g. `/var`, `/tmp` etc.), so it needs to be thought how to present this to the user.

I don't know your code though, so it may be simple and/or straightforward. Also, a first release may adopt a very simple approach, not necessarily a sophisticated one.

## Conclusion

Please publish your fork! Ping me here when you're done, and I'll have a review, then we can follow up.

**Comment by saveriomiroddi** [comment]
And it goes without saying, thanks for your proposition :smile:

**Comment by selbitschka** [comment]
Fork is online https://github.com/selbitschka/zfs-installer

I documented the changes I made so they are easy to follow.

I tried to implement all features according your style. Therefore there is a variable ZFS_XXX_ to allow scripting and a whiptail input for all features.

**Comment by pepa65** [comment]
With all the options for additional storage sets, wouldn't it be clearer and more flexible for users to be able to specify the extra sets they would like to have like: ZFS_SETS=/home:/var/cache:/var/log:/opt:/data instead of using a preselected (and therefore limited) set of variables like: ZFS_HOME_SET, ZFS_VAR_SET and ZFS_OPT_SET?

In my case, I would like /data to be a separate set, and I would only want /var/log and /var/cache in separate sets, but not the other preselected subdirectories of /var. It would probably clean up the code as well, as you can loop over ZFS_SETS.

**Comment by saveriomiroddi** [comment]
> With all the options for additional storage sets, wouldn't it be clearer and more flexible for users to be able to specify the extra sets they would like to have like: ZFS_SETS=/home:/var/cache:/var/log:/opt:/data instead of using a preselected (and therefore limited) set of variables

Yes, absolutely. And that's a type of UX problem I've anticipated :smile: 

As a matter of fact, some time ago, when thinking about this feature, I had in mind to allow the user to set a format like `<dataset1>=<mountpoint1>:...:<datasetN>=<mountpointN>`. Possibly, to make UX even smoother, to use a [Whiptail checklist](https://saveriomiroddi.github.io/Shell-scripting-adventures-part-3/#check-list) with some common entries, and the last one allowing the user to specify their own (I guess, in a subsequent widget).

**Comment by saveriomiroddi** [comment]
Of course, this feature could be implemented iteratively, although, implementing fixed datasets with multiple env variables, then allowing customization via a single env variable, would break the API (could be a minor issue, as I guess not many people use the unattended installation feature).

@selbitschka I'll review the fork over the next week, and then we can follow up.

**Comment by selbitschka** [comment]
> > With all the options for additional storage sets, wouldn't it be clearer and more flexible for users to be able to specify the extra sets they would like to have like: ZFS_SETS=/home:/var/cache:/var/log:/opt:/data instead of using a preselected (and therefore limited) set of variables

> As a matter of fact, some time ago, when thinking about this feature, I had in mind to allow the user to set a format like `<dataset1>=<mountpoint1>:...:<datasetN>=<mountpointN>`. Possibly, to make UX even smoother, to use a [Whiptail checklist](https://saveriomiroddi.github.io/Shell-scripting-adventures-part-3/#check-list) with some common entries, and the last one allowing the user to specify their own (I guess, in a subsequent widget).

<datasetX>=<mountpointx> could be problematic if users are not fully aware of ZFS datasets pitfalls. For Example you need /var if you want /var/log but /var most likely should not be mounted and can be created with "-o canmount=off" or /var/log can use "-o com.sun:auto-snapshot=false" etc. If you allow this kind of dataset option the user need to know what's to do because the order of datasets, the path (i.e. 'rpool/encrytped/root/data'), and all options need to be set right.

That why I implemented the '/var' and 'opt' dataset option like that.

For advanced users it could be better to stop the script and tell them "we have created this pools and set - now its your turn to finish if you need something fancy". Then the user can create all other sets in a second terminal and afterwards continue the installation.

Otherwise you end up in UX hell, <datasetX>=<mountpointX>=<optionsX>: ... and plenty of validation code.

**Comment by pepa65** [comment]
I think /var is obviously a special case, and if /var/xxx gets listed, the code will need to automatically include /var but with the indication that it doesn't need to be mounted (so the /var on root can be used as a mountpoint).

For most users, I don't think these options using ZFS_xxx= get used at all, and we don't have to go overboard in allowing for all kinds of exotic options.
I am not a basic user, but I would not like to have to go to a shell and start doing things by hand in the middle of the script...

**Comment by saveriomiroddi** [comment]
@selbitschka so! I had a look at the fork. it's very interesting ideas. as of now, it can't be directly integrated, as it needs typical production refinements (splitting in multiple commits, documentation, testing etc.), however, I'll convert every idea into an issue for tracking and implementing

The highest priority issue I'll address is actually the asynchronous swap volume creation. I've received no reports until now, but it absolutely makes sense to assume asynchronousness. I'll take a different strategy though - rather than using `sleep`, I'll wait on the device to be created (a simple bash conditional + loop should do).

As soon as I'll create the new tracking issues, I'll close this one, and put reference.

Thanks for your participation @selbitschka  @pepa65! :+1:

**Comment by selbitschka** [comment]
Great to hear that you like some of my improvements.

The swap "sleep" hack was introduced as quick and dirty fix since this came up during the production installation of my laptop, I didn't want to do fancy zvol availability stuff. But it would be definitive the better solution ;).

Awaiting the new issues.

**Comment by saveriomiroddi** [comment]
Closing; I've created #136, #137, and #138. I have no timeline because I'm very busy with a significant project, but the issue will make sure nothing is forgotten :smile:

Thanks for the participation :slightly_smiling_face:

**Comment by saveriomiroddi** [comment]
I'm implementing this now (#137). The cool thing is that the overall architecture of the script doesn't need to be changed. If a user wants to encrypt the root dataset (as opposed to the root pool), they will be able to do this (by specifying the dataset options). I should have this ready in a couple of days.

**Comment by saveriomiroddi** [comment]
Just released the functionality with the new version. When encrypting a dataset (as opposed to the pool), the password is asked in the terminal.
