### ISSUE TITLE
c_boot_partition_size too small

### ISSUE THREAD

**Issue by Kihltech** [saveriomiroddi/zfs-installer#145]
I've just recently been in trouble with a too small bpool partition. 
512MB was only good for 3 kernels and 3 snapshots. (Ubuntu 20.04 server) 

I would suggest a default value of 2048MB and the option to change it in the guided installer similar to other parameters. 
If I were to re-setup my servers I would use 8192MB because I have the space and it's a pain to fight with grub and kernel updates when running out of space... 

Great tool by the way!

**Comment by saveriomiroddi** [comment]
Rejoice, the functionality has been merged in master! :tada: :partying_face:

I'll release it soon - those in need before release time, can use master.

Regarding the default size, I'll change it, but it will take some time, because I've found a minor bug - EFI system partition and boot pool partition share the same size, which is wrong (but fortunately, it doesn't harm).

**Comment by saveriomiroddi** [comment]
Thanks for the compliment by the way, and happy to hear that the tool is useful! :star_struck:

**Comment by saveriomiroddi** [comment]
OK, also the bug and the increase of boot pool default size have been merged in master! Will release soon in stable.

**Comment by meonkeys** [comment]
Shoot, I ran into this problem too. Is there an easy way to grow my `bpool` without starting over from scratch? Maybe shrink `rpool` and grow `bpool` by a couple gibibytes?

**Comment by Kihltech** [comment]
> 
> 
> Shoot, I ran into this problem too. No space left after 3 kernels. Is there an easy way to grow my `bpool` without starting over from scratch? Maybe shrink `rpool` and grow `bpool` by a couple gibibytes?
> 
> Aha... I was able to free up some space by destroying snapshots. I forgot I have `zfs-auto-snapshot` installed. I ran `sudo zfs set com.sun:auto-snapshot=false bpool` to keep the boot partition from filling up.
> 
> I'd still like a larger bpool to have room for the snapshots too. But at least I was able to free up enough space to install another kernel.

Exactly my experience and how I needed to fix it. 

Even though I think it is possible to resize the bpool, I think it's way harder than just starting from scratch.

Thanks for the fix and addition of customization - looking forward to try it out!
