### ISSUE TITLE
how to use another set of drives for Home ?

### ISSUE THREAD

**Issue by JOduMonT** [saveriomiroddi/zfs-installer#150]
Hey; Thank for your very useful scripts, it save me a lot of time ;)

On one of my computer I have 5 drives and I would like to make 2 mirror use

2 drives for the main OS aka pool/dataset root and boot (_these drives are SDD and smaller_)
and 2 drives for the /home (_while these one are SATA and bigger_)

I saw the [script where you could set more than one dataset](https://github.com/saveriomiroddi/zfs-installer/issues/135) but still even with this one I'm can't figure or to make 2 mirrors and specify which dataset goes on which mirror

@selbitschka  or @saveriomiroddi Do you know how to figure this case scenario ?

**Comment by JOduMonT** [comment]
so it is probably not the best, and I still would like your point of view on this, but
I created a new pool for home [inspired from this command](https://github.com/saveriomiroddi/zfs-installer/blob/master/install-zfs.sh#L1001-L1006) 
then it didn't mount automatically as expected, so I made a service [based on this tuto](https://0p.no/2019/12/22/zfs_encrypted_home.html) then reboot on my Ubuntu Live Key and move my home to the new pool than reboot.

```
[Unit]
Description=Load %I encryption keys
Before=systemd-user-sessions.service
Before=zfs-mount.service
After=zfs-import.target

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/bash -c 'systemd-ask-password "Encrypted ZFS password for %I" --no-tty  | zfs load-key -a'

[Install]
WantedBy=zfs-mount.service

```

Presently, it asks me 2 passwords during the boot process
but every is as I expected:
- system on SDD
- data on SATA
- and everything under ZFS.

How would you manage the boot sequence, do you think it is possible to remove my "dumb service" ?

**Comment by JOduMonT** [comment]
While I have your attention.
When I create a 3rd pool encrypted on my nvme which I would like to use for swap and tmp file
the system don't boot properly.

all pool and dataset are open zpool list and zfs list show the right info
but /home don't mount even if the mountpoint is set properly (it work when I destroy the nvme pool).

**Comment by saveriomiroddi** [comment]
Hello!

So, the project issue tracker is for issue related to the project itself, so I'll split the answer in two - related and unrelated concepts.

## Related

I've reviewed the option to add support for extra pools (or at least, for another one), and I can't put this in the plan - at least for a (very) long time; it's not a trivial change, and it requires some other preparation work (ie. #137) in order to be useful.

## Unrelated

I can't offer support for issues unrelated to the project itself. I can offer private consultancy on this, but I don't have a long experience on this, so it would likely be expensive and inefficient. The best place for these requests is the [`zfs-discuss` mailing list](https://zfsonlinux.topicbox.com/groups/zfs-discuss). There may be a chat channel, but I've never used one.

**Comment by JOduMonT** [comment]
> I can't offer support for issues unrelated to the project itself. I can offer private consultancy on this, but I don't have a long experience on this, so it would likely be expensive and inefficient. The best place for these requests is the [`zfs-discuss` mailing list](https://zfsonlinux.topicbox.com/groups/zfs-discuss). There may be a chat channel, but I've never used one.

Thank for your lovely reply.
FYI: I opted for a different approach, I left /home in the main pool than mount another pool (after the installation) mount in /srv than put all my data there. It will might sound silly, but this have the advantage of temporary files such as from OBS Studio and OpenShot are under SSD and make the apps a little bit faster (but it might be just in my head too).

**Comment by saveriomiroddi** [comment]
Hello!

Sorry for the unpleasant reply :pray:. I've just enabled the GitHub [discussions](https://github.com/saveriomiroddi/zfs-installer/discussions/151), which are actually an ideal solution for differentiating support/feature requests and issue :partying_face:
