### ISSUE TITLE
v0.4x breaks update-grub

### ISSUE THREAD

**Issue by alexw1982** [saveriomiroddi/zfs-installer#199]
hi,

thanks for the great work. the new release breaks update-grub on ubuntu 20.04 server. No issues with 0.3x version. You can install it after a upgrade-grub (e.g. via kernel update) the system becomes unbootable as grub cannot find initrd files etc.

**Comment by saveriomiroddi** [comment]
Disaster! :scream: I'll check this out over the next week :smile: Thanks for the report!

**Comment by alexw1982** [comment]
No worries - after 1.5 days I finally got the idea to use an old release - I like the old dataset Lay-out more anyway 😜

**Comment by saveriomiroddi** [comment]
It seems that Ubuntu Server expects the boot filesystem to be on a specific path (`bpool/BOOT/ROOT`), when using the new procedure. I have a fix, but I need to make it fit cleanly.

**Comment by alexw1982** [comment]
With 0.3.x it did work without it. I installed the latest 20.04.2 using that version without an issue. It only nags with an error message when updating grub that it can’t find bpool/BOOT/ROOT but aside from that it works and it also creates entries for newly installed kernels

**Comment by saveriomiroddi** [comment]
I've noticed (after long hours) that the official procedure does not directly support Ubuntu Server :cry:.

As of now, the only way for this script to install Ubuntu Server is to use v0.3.x, therefore, I've updated the README.

The solution is to integrate the old and new procedures, but that's something that I don't have resources to do :crying_cat_face:. I'm opening a tracking issue, though.

**Comment by alexw1982** [comment]
Thanks for investigating- regardless of the outcome: thanks a bunch for your efforts!
