### ISSUE TITLE
Openzfs Ppa crashes Ubuntu server 20.04 installer

### ISSUE THREAD

**Issue by alexw1982** [saveriomiroddi/zfs-installer#200]
When selecting zfs_ppa the Ubuntu server 20.04 installer would always crash when formatting the partition - this does not happen without the ppa set to 1

**Comment by saveriomiroddi** [comment]
Thanks for reporting again :)

Interesting one (because it may not be an issue with the script :grimacing:). I'll check what happens with the previous version of the script, and follow up.

**Comment by alexw1982** [comment]
I also found this very strange but I reproduced it at least 10x times. Most likely an issue with subiquity installer but users of your awesome script should be aware in case this happens and not try 10x again :-)

**Comment by saveriomiroddi** [comment]
Hello! I've just fixed the issue (see linked PR). It seems that there is another issue though, which I'm fixing separately.

**Comment by saveriomiroddi** [comment]
[Fixed](https://github.com/saveriomiroddi/zfs-installer/pull/202) also the other issue, which is due to a change in 20.04.2. It seems that they've changed a few things in it, which broke the script in several ways.

**Comment by saveriomiroddi** [comment]
I've disabled the PPA support on Ubuntu Server; it breaks the procedure (it's not a problem of the script), but it's not obviously clear why.
