### ISSUE TITLE
Striped+mirrored setup with 4 (or possibly more) disks

### ISSUE THREAD

**Issue by joellimberg** [saveriomiroddi/zfs-installer#223]
(This is a feature request, somewhat related in spirit to the ideas in issues #109 and #111)

Currently, it seems that on a 4-disk system, selecting the "mirror" type mirrors all 4 disks.

This is actually what I would expect, but it would be nice if an additional option existed to create a striped+mirrored setup (`zpool create … mirror DISK1 DISK2 mirror DISK3 DISK4`).

For simplicity, maybe the striped+mirrored option could be shown only if exactly 4 disks are selected?

**Comment by saveriomiroddi** [comment]
Hello!

The implementation is not intrusive, so it shouldn't be a problem. The difficult part is thinking about a good UX which is simple but flexible.

I'm inclined not to add a special-case solution, however, I have something in mind that should work.

Will work on this on my next biweekly cycle :smile:

**Comment by joellimberg** [comment]
You'll probably have a better idea for the UI, but just as a thought: zfs-installer could show a striped+mirrored option (not sure of the correct zfs terminology for this) if and only if there is an even number of disks (4 or more).

**Comment by joellimberg** [comment]
I created a basic implementation (that only supports exactly 4 disks) for my own use: diff here: https://github.com/saveriomiroddi/zfs-installer/compare/master...joellimberg:feature/striped-mirrored-disks?expand=1

**Comment by saveriomiroddi** [comment]
Released :smile:
