### ISSUE TITLE
Post-zfs-installer help screen wording

### ISSUE THREAD

**Issue by joellimberg** [saveriomiroddi/zfs-installer#224]
I've run zfs-installer only in a Virtualbox VM for testing (Ubuntu 20.04 server), so this might not occur on an actual physical machine, but:

zfs-installer shows this message:

<img width="824" alt="Screen Shot 2021-07-05 at 20 28 53" src="https://user-images.githubusercontent.com/875872/124504201-a9b34900-ddcf-11eb-98ab-e7b54ccd3cfb.png">

But the Ubuntu installer partitioning screen doesn't actually include a disk named "/dev/sda4":

<img width="1017" alt="Screen Shot 2021-07-05 at 20 30 26" src="https://user-images.githubusercontent.com/875872/124504323-e7b06d00-ddcf-11eb-814d-29de02e3451d.png">

I assume sda4 refers to the 4th partition on the first ("a") disk? If this disk naming confusion is present on non-VM setups, maybe a more verbose help message (about what partition needs to be formatted, etc) would help non-experienced users like me.

For reference, the first disk selection screen in zfs-installer lists these disks:

<img width="837" alt="Screen Shot 2021-07-05 at 20 35 33" src="https://user-images.githubusercontent.com/875872/124504646-905ecc80-ddd0-11eb-9298-795b16a097b9.png">

---

Additionally, on first run I messed up by misreading `“Do not continue in this terminal (tap Enter) now!”` (read it as "tap enter now"), but it actually means the opposite. Maybe “`*Do not* tap enter before completing the steps above`” would be clearer?

**Comment by saveriomiroddi** [comment]
Hello!

Thanks for the issue. I need to review it carefully, but I think it's a bug. In the upcoming two weeks, I have cycles to dedicate to ZFS, so I'll take care of this and the other issue :smile:

**Comment by saveriomiroddi** [comment]
Hello!

I've improved the description and released it. See referenced PR for notes.

Example here:

![dialog](https://user-images.githubusercontent.com/1595356/124516909-0835f280-dde3-11eb-9f20-0bc3c2f95f6b.png)

![subiquity](https://user-images.githubusercontent.com/1595356/124516917-0cfaa680-dde3-11eb-86fd-082aed7f4590.png)

**Comment by joellimberg** [comment]
Thanks for your great work on this project!
