### ISSUE TITLE
works with zfs 2.1.0

### ISSUE THREAD

**Issue by stayprivate** [saveriomiroddi/zfs-installer#229]
Would like to report that it works with zfs 2.1.0 from the jonathonf ppa.  Once everythin was installed and running, I added the ppa and instead of doing an apt upgrade which breaks everything, I did  apt install zfs-dmks and it works.  I did not try to modify the script to do this as of out of time.  

Thanks

**Comment by saveriomiroddi** [comment]
Hello!

Thanks for the report :blush:

I've actually tested 2.1 as well and it works as expected. I don't have clear what you mean with `doing an apt upgrade which breaks everything`, though :thinking:

**Comment by stayprivate** [comment]
Hum I though I already reply but can't see it.

What I meant is that after the whole installation was completed I added the ppa then did  apt update and apt upgrade. The upgrade failed with dependencies related messages.  Error messages suggested using --fix-install but to no avail. I reinstall from scratch, but after adding the pps I did apt update and apt install zfs-dmks and NOT an apt upgrade. That did the trick. 3 packages became obsolete and apt autoremove got rid of them.  After that an apt upgrade worked fine.

Unrelated question, I tested a Mirror setup ( 2 disks), I replace one disc with a blank one. After I manually created the partitions I was able to "zpool replace" the 2 zpool partitions. I'm not sure the second disk is bootable though.  Before I dig deeper into this I wonder it there is documentation/tool to take care of that automagicaly?  

Cheers,
Mario

**Comment by saveriomiroddi** [comment]
Hello! Thanks for the report. So,

> What I meant is that after the whole installation was completed I added the ppa then did apt update and apt upgrade. The upgrade failed with dependencies related messages. Error messages suggested using --fix-install but to no avail. I reinstall from scratch, but after adding the pps I did apt update and apt install zfs-dmks and NOT an apt upgrade. That did the trick. 3 packages became obsolete and apt autoremove got rid of them. After that an apt upgrade worked fine.

This is very odd, but this specific workflow is outside the control of the script.

The base workflow of the script installs, on Ubuntu, the packages `libzfs2linux zfs-initramfs zfs-zed zfsutils-linux` from the standard repository.

When it's intended to use the PPAS on the installed system, it's best to set the `ZFS_USE_PPA=1` env variable, so that the script will preset the PPA and install its packages in the destination system; this way, user error is prevented, and I'm also able to diagnose the problem by looking at the logs.

> Unrelated question, I tested a Mirror setup ( 2 disks), I replace one disc with a blank one. After I manually created the partitions I was able to "zpool replace" the 2 zpool partitions. I'm not sure the second disk is bootable though. Before I dig deeper into this I wonder it there is documentation/tool to take care of that automagicaly?

I'm moving this to the GitHub discussions, which is a better location.

**Comment by saveriomiroddi** [comment]
> Unrelated question, I tested a Mirror setup ( 2 disks), I replace one disc with a blank one. After I manually created the partitions I was able to "zpool replace" the 2 zpool partitions. I'm not sure the second disk is bootable though. Before I dig deeper into this I wonder it there is documentation/tool to take care of that automagicaly?

Answered here: https://github.com/saveriomiroddi/zfs-installer/discussions/231.

**Comment by ahmgithubahm** [comment]
Link above is now https://github.com/64kramsystem/zfs-installer/discussions/231

**Comment by 64kramsystem** [comment]
> Discussions link above is now #231

Thanks!
