### ISSUE TITLE
Ubuntu Server installation fails because of missing efibootmgr package

### ISSUE THREAD

**Issue by saveriomiroddi** [saveriomiroddi/zfs-installer#45]
The package efibootmgr is missing; see #43

**Comment by saveriomiroddi** [comment]
@kongkrit: this fixes the efibootmgr problem. I've released it in the stable branch, and performed a full Ubuntu Server installation (without encryption/security packages installed).

**Comment by kongkrit** [comment]
@saveriomiroddi will test all the features and report back to you ASAP. thanks very much for the fix.

**Comment by kongkrit** [comment]
@saveriomiroddi,

I installed Ubuntu server 18.04.3 LTS without root encryption and it now works without having to do anything besides launching your script. Thanks!

**Comment by saveriomiroddi** [comment]
@kongkrit thanks for your reports and for your patience :smile:

**Comment by kongkrit** [comment]
@saveriomiroddi it's you i have to thank big time for your great patience. i hope the tool becomes useful for many people, as it has for me. maybe canonical will pull some of this into ubuntu focal? (*^_^*)
