### ISSUE TITLE
v_system_disks unbound variable

### ISSUE THREAD

**Issue by sefianix** [saveriomiroddi/zfs-installer#48]
find_disks reports back nothing for v_system_disks.

getting line 265: v_system_disks: unbound variable

but ls -al /dev/disk/by-id/ is not empty.

**Comment by saveriomiroddi** [comment]
Hello!

Can you post the result of:

```sh
  while read -r disk_id; do
    echo "## DEVICE: $disk_id ################################"
    echo
    udevadm info --query=property "$(readlink -f "$disk_id")"
    echo
  done <<< "$(find /dev/disk/by-id -regextype awk -regex '.+/(ata|nvme|scsi)-.+' -not -regex '.+-part[0-9]+$' | sort)"
```

**Comment by sefianix** [comment]
## DEVICE: /dev/disk/by-id/nvme-THNSN51T02DUK_NVMe_TOSHIBA_1024GB_86HS100IT1CT ################################

DEVLINKS=/dev/disk/by-id/nvme-eui.00080d02000c3e02 /dev/disk/by-label/rpool /dev/disk/by-path/pci-0000:3d:00.0-nvme-1 /dev/disk/by-uuid/10367005504290435713 /dev/disk/by-id/nvme-THNSN51T02DUK_NVMe_TOSHIBA_1024GB_86HS100IT1CT
DEVNAME=/dev/nvme0n1
DEVPATH=/devices/pci0000:00/0000:00:1d.0/0000:3d:00.0/nvme/nvme0/nvme0n1
DEVTYPE=disk
ID_FS_LABEL=rpool
ID_FS_LABEL_ENC=rpool
ID_FS_TYPE=zfs_member
ID_FS_USAGE=filesystem
ID_FS_UUID=10367005504290435713
ID_FS_UUID_ENC=10367005504290435713
ID_FS_UUID_SUB=3111965663500497905
ID_FS_UUID_SUB_ENC=3111965663500497905
ID_FS_VERSION=5000
ID_MODEL=THNSN51T02DUK NVMe TOSHIBA 1024GB
ID_PART_TABLE_TYPE=gpt
ID_PART_TABLE_UUID=2f44b6c3-752b-433a-8321-33ec0805a0b3
ID_PATH=pci-0000:3d:00.0-nvme-1
ID_PATH_TAG=pci-0000_3d_00_0-nvme-1
ID_SERIAL=THNSN51T02DUK NVMe TOSHIBA 1024GB_86HS100IT1CT
ID_SERIAL_SHORT=86HS100IT1CT
ID_WWN=eui.00080d02000c3e02
MAJOR=259
MINOR=0
SUBSYSTEM=block
TAGS=:systemd:
USEC_INITIALIZED=10840453

## DEVICE: /dev/disk/by-id/nvme-eui.00080d02000c3e02 ################################

DEVLINKS=/dev/disk/by-id/nvme-THNSN51T02DUK_NVMe_TOSHIBA_1024GB_86HS100IT1CT /dev/disk/by-uuid/10367005504290435713 /dev/disk/by-id/nvme-eui.00080d02000c3e02 /dev/disk/by-label/rpool /dev/disk/by-path/pci-0000:3d:00.0-nvme-1
DEVNAME=/dev/nvme0n1
DEVPATH=/devices/pci0000:00/0000:00:1d.0/0000:3d:00.0/nvme/nvme0/nvme0n1
DEVTYPE=disk
ID_FS_LABEL=rpool
ID_FS_LABEL_ENC=rpool
ID_FS_TYPE=zfs_member
ID_FS_USAGE=filesystem
ID_FS_UUID=10367005504290435713
ID_FS_UUID_ENC=10367005504290435713
ID_FS_UUID_SUB=3111965663500497905
ID_FS_UUID_SUB_ENC=3111965663500497905
ID_FS_VERSION=5000
ID_MODEL=THNSN51T02DUK NVMe TOSHIBA 1024GB
ID_PART_TABLE_TYPE=gpt
ID_PART_TABLE_UUID=2f44b6c3-752b-433a-8321-33ec0805a0b3
ID_PATH=pci-0000:3d:00.0-nvme-1
ID_PATH_TAG=pci-0000_3d_00_0-nvme-1
ID_SERIAL=THNSN51T02DUK NVMe TOSHIBA 1024GB_86HS100IT1CT
ID_SERIAL_SHORT=86HS100IT1CT
ID_WWN=eui.00080d02000c3e02
MAJOR=259
MINOR=0
SUBSYSTEM=block
TAGS=:systemd:
USEC_INITIALIZED=10840453

**Comment by sefianix** [comment]
I did get past the problem.  my workaround was commenting out lines 266-267,269-270. Installation went fine after that.  Thank you for the script!

**Comment by saveriomiroddi** [comment]
@sefianix thanks for your feedback! it seems that `udevadm info`, which is used to select the disks, doesn't give enough information to make a clear choice. I've relaxed the conditions, so that the disks of systems like yours will always show.
