### ISSUE TITLE
Add Ubuntu Server 18.04 LTS non-live installer support

### ISSUE THREAD

**Issue by felix-schwarz** [saveriomiroddi/zfs-installer#53]
The `ubuntu-18.04.3-live-server-amd64.iso` installer does not work on many computers that the `ubuntu-18.04.3-server-amd64.iso` installer works on very well.

Unfortunately, this script does not work with the non-live version of the Ubuntu Server 18.04.3 installer.

**Comment by saveriomiroddi** [comment]
Hello Felix, thanks for the report. I wasn't aware that such version existed. I'll have a look and get back.

**Comment by felix-schwarz** [comment]
Thanks so much @saveriomiroddi!

**Comment by saveriomiroddi** [comment]
I just had a look at the non-live (["alternate"](http://cdimage.ubuntu.com/releases/18.04/release)), and base on my limited knowledge, it's not possible to integrate this distribution without considerable work.

This Ubuntu Server version uses Busybox as environment, which lacks all the tools currently used in the installer (like apt, and even rsync).

If somebody knowledgeable can help, I'll definitely discuss it, but as of now, I can't add this support.

I'm leaving this issue open for a month, in case somebody wants to/can contribute.

**Comment by felix-schwarz** [comment]
Thanks for looking into it regardless!

I found an alternative way and decided to share my notes here, hoping it'll be useful to others: https://gist.github.com/felix-schwarz/2a9ef78effb26e9d940b9fcbfb1285c1

**Comment by saveriomiroddi** [comment]
> Thanks for looking into it regardless!
> 
> I found an alternative way and decided to share my notes here, hoping it'll be useful to others: https://gist.github.com/felix-schwarz/2a9ef78effb26e9d940b9fcbfb1285c1

So! I'm a bit confused :grimacing: 

The instructions you've posted are valid for a standard debian-based distro. How do you execute them in the context of a non-live ("alternate") Ubuntu Server live session?

When I've tried it, I was able to only get a busybox environment - and on it, the script you've mention would not run. Therefore, now I realize that it's possible that there is a way to get a "full" debian-based environment.

Could you post the exact instructions (including the source ISO) on an Ubuntu *non-live* session, that allow you to run the script you've posted? If this is possible, I can review the integration in the `zfs-installer`.

**Comment by felix-schwarz** [comment]
Those instructions require Ubuntu 18.04 to be installed to an ext4 partition first (briefly mentioned in step "Basic install") and then reboot into it - at which point apt, bash, etc. are all available.

When placing that install partition at the end of the HDD/SSD, it can later be removed and the zpool be resized to also use that space. Or it could be repurposed as a classic swap partition.

**Comment by saveriomiroddi** [comment]
> Those instructions require Ubuntu 18.04 to be installed to an ext4 partition first (briefly mentioned in step "Basic install") and then reboot into it - at which point apt, bash, etc. are all available.
> 
> When placing that install partition at the end of the HDD/SSD, it can later be removed and the zpool be resized to also use that space. Or it could be repurposed as a classic swap partition.

Sorry, let me clarify.

You have (I assume) a "non-live" Ubuntu Server ISO, and you boot from it. How do you get to a terminal where it's possible to run commands like your script?

**Comment by saveriomiroddi** [comment]
Closing the issue, as, based on the available information, scripts revolving around standard Unix tools won't work on a non-live ("alternate") Ubuntu server version.

**Comment by felix-schwarz** [comment]
> You have (I assume) a "non-live" Ubuntu Server ISO, and you boot from it. How do you get to a terminal where it's possible to run commands like your script?

I've run these commands in the installed Ubuntu Server instance, after booting into it.
