### ISSUE TITLE
"No suitable disks have been found" with non /dev/sdX disks

### ISSUE THREAD

**Issue by Mek101** [saveriomiroddi/zfs-installer#73]
The script always stops at "find_suitable_disks" while there aren't sdX disks available, even if there are other disks available (in my case /dev/mmcblk0), even after setting ZFS_SELECTED_DISKS=/dev/mmcblk0, ZFS_SELECTED_DISKS="/dev/mmcblk0" or by id.

(manual copy of the disk log)
mmc-HBGE3e__0xfda03013 -> ../../mmcblk0
mmc-HBGE3e__0xfda03013-part1 -> ../../mmcblk0p1
usd-SanDisk_Cruzer_Glide_4C531001590307114112 -0:0 -> ../dev/sda
usd-SanDisk_Cruzer_Glide_4C531001590307114112 -0:0-part1 -> ../dev/sda1

**Comment by saveriomiroddi** [comment]
Hello! Please post the entire disks log.

**Comment by Mek101** [comment]
It's all there was written

**Comment by saveriomiroddi** [comment]
Yikes! Ok, well, I think the fix is easy. Before that though, can you tell which machine (model) you're using? Is this a single board computer, or a budget laptop?

**Comment by Mek101** [comment]
A budget laptop: Acer Aspire one Cloudbook 14

**Comment by saveriomiroddi** [comment]
OK. Try the script at https://git.io/Jv9wr, it should work. I can't confirm without my hands on the device, but adding the support itself is trivial.

**Comment by Mek101** [comment]
Unfortunately I had to rollback to ext4, since I needed to have the device operating by tomorrow.
I should add that after that, I still had numerous problems installing Linux mint in that machine, where basically the bios seemed to not see the EFI boot entry and I had to rollback with the mbr.
If and when the devices isn't needed anymore, I will experiment on it, that's for sure.

**Comment by saveriomiroddi** [comment]
Ach, sorry to hear that :scream: I'll merge in anyway, between today and tomorrow, as I think it's worth having for people who want to experiment.
