### ISSUE TITLE
Install logs contain sensitive information while it is explicitly said they do not

### ISSUE THREAD

**Issue by Zapunidi** [saveriomiroddi/zfs-installer#80]
readme.md says:  "It doesn't contain any information aside what required for performing the installation; it can be trivially inspected, as it's a standard Bash debug output."
But in reality it contains root password used in installation in plain text.

Suggestion to change readme.md to hide sensitive information before making logs public.

**Comment by saveriomiroddi** [comment]
Hello!

That was intentional, ie. a bug :slightly_smiling_face: 

I've fixed the code, by disabling logging for the sections where (the remaining) confidential information (=passwords) was logged, and released the new version :slightly_smiling_face:
