### ISSUE TITLE
Support for Ubuntu 20.04 Server

### ISSUE THREAD

**Issue by doughnet** [saveriomiroddi/zfs-installer#81]
Support for Ubuntu 20.04 Server

Does not run at all because version supported is 18.04 only.

**Comment by saveriomiroddi** [comment]
Hello! I've done a good deal of preparatory work today, but unfortunately, Ubiquity interferes with ZFS pools, making the current installation impossible via Ubiquity (possibly, it works using `debootstrap` inside a `$ZFS_OS_INSTALLATION_SCRIPT`).

I've submitted [a bug](https://bugs.launchpad.net/ubuntu/+source/ubiquity/+bug/1875045) in the Ubuntu bug tracker.

If somebody with time and skills can write a script to be used via `$ZFS_OS_INSTALLATION_SCRIPT`, it would be appreciated, but I don't have the resources now :slightly_smiling_face:.

**Comment by saveriomiroddi** [comment]
It seems like I've diagnosed the problem, and found a workaround. I'm testing it, then I'll release it.
